# Generated by Django 4.2.1 on 2023-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useractivity_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='last_request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
